library angular2.src.testing.test_injector.ng_deps.dart;

import 'test_injector.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'package:angular2/core.dart' show APP_ID, APPLICATION_COMMON_PROVIDERS, AppViewManager, DirectiveResolver, DynamicComponentLoader, Injector, NgZone, Renderer, Provider, ViewResolver, provide;
import 'package:angular2/src/animate/animation_builder.dart' show AnimationBuilder;
import 'package:angular2/src/mock/animation_builder_mock.dart' show MockAnimationBuilder;
import 'package:angular2/src/core/linker/proto_view_factory.dart' show ProtoViewFactory;
import 'package:angular2/src/core/reflection/reflection.dart' show Reflector, reflector;
import 'package:angular2/src/core/change_detection/change_detection.dart' show IterableDiffers, defaultIterableDiffers, KeyValueDiffers, defaultKeyValueDiffers, ChangeDetectorGenConfig;
import 'package:angular2/src/facade/exceptions.dart' show ExceptionHandler;
import 'package:angular2/src/core/linker/pipe_resolver.dart' show PipeResolver;
import 'package:angular2/src/compiler/xhr.dart' show XHR;
import 'package:angular2/src/platform/dom/dom_adapter.dart' show DOM;
import 'package:angular2/src/mock/directive_resolver_mock.dart' show MockDirectiveResolver;
import 'package:angular2/src/mock/view_resolver_mock.dart' show MockViewResolver;
import 'package:angular2/src/mock/mock_location_strategy.dart' show MockLocationStrategy;
import 'package:angular2/src/router/location_strategy.dart' show LocationStrategy;
import 'package:angular2/src/mock/ng_zone_mock.dart' show MockNgZone;
import 'test_component_builder.dart' show TestComponentBuilder;
import 'package:angular2/platform/common_dom.dart' show EventManager, EVENT_MANAGER_PLUGINS, ELEMENT_PROBE_PROVIDERS;
import 'package:angular2/src/facade/collection.dart' show ListWrapper;
import 'package:angular2/src/facade/lang.dart' show FunctionWrapper, Type;
import 'package:angular2/src/core/linker/view_pool.dart' show AppViewPool, APP_VIEW_POOL_CAPACITY;
import 'package:angular2/src/core/linker/view_manager_utils.dart' show AppViewManagerUtils;
import 'package:angular2/src/platform/dom/dom_tokens.dart' show DOCUMENT;
import 'package:angular2/src/platform/dom/dom_renderer.dart' show DomRenderer;
import 'package:angular2/src/platform/dom/shared_styles_host.dart' show DomSharedStylesHost;
import 'package:angular2/src/platform/dom/shared_styles_host.dart' show SharedStylesHost;
import 'package:angular2/src/platform/dom/events/dom_events.dart' show DomEventsPlugin;
import 'package:angular2/src/web_workers/shared/serializer.dart' show Serializer;
import 'utils.dart' show Log;
import 'package:angular2/src/compiler/compiler.dart' show COMPILER_PROVIDERS;
import 'package:angular2/src/platform/dom/dom_renderer.dart' show DomRenderer_;
import 'package:angular2/src/core/linker/dynamic_component_loader.dart' show DynamicComponentLoader_;
import 'package:angular2/src/core/linker/view_manager.dart' show AppViewManager_;
import 'package:angular2/core.ng_deps.dart' as i0;
import 'package:angular2/src/animate/animation_builder.ng_deps.dart' as i1;
import 'package:angular2/src/mock/animation_builder_mock.ng_deps.dart' as i2;
import 'package:angular2/src/core/linker/proto_view_factory.ng_deps.dart' as i3;
import 'package:angular2/src/core/reflection/reflection.ng_deps.dart' as i4;
import 'package:angular2/src/core/change_detection/change_detection.ng_deps.dart' as i5;
import 'package:angular2/src/facade/exceptions.ng_deps.dart' as i6;
import 'package:angular2/src/core/linker/pipe_resolver.ng_deps.dart' as i7;
import 'package:angular2/src/compiler/xhr.ng_deps.dart' as i8;
import 'package:angular2/src/platform/dom/dom_adapter.ng_deps.dart' as i9;
import 'package:angular2/src/mock/directive_resolver_mock.ng_deps.dart' as i10;
import 'package:angular2/src/mock/view_resolver_mock.ng_deps.dart' as i11;
import 'package:angular2/src/mock/mock_location_strategy.ng_deps.dart' as i12;
import 'package:angular2/src/router/location_strategy.ng_deps.dart' as i13;
import 'package:angular2/src/mock/ng_zone_mock.ng_deps.dart' as i14;
import 'test_component_builder.ng_deps.dart' as i15;
import 'package:angular2/platform/common_dom.ng_deps.dart' as i16;
import 'package:angular2/src/core/linker/view_pool.ng_deps.dart' as i17;
import 'package:angular2/src/core/linker/view_manager_utils.ng_deps.dart' as i18;
import 'package:angular2/src/platform/dom/dom_tokens.ng_deps.dart' as i19;
import 'package:angular2/src/platform/dom/dom_renderer.ng_deps.dart' as i20;
import 'package:angular2/src/platform/dom/shared_styles_host.ng_deps.dart' as i21;
import 'package:angular2/src/platform/dom/events/dom_events.ng_deps.dart' as i22;
import 'package:angular2/src/web_workers/shared/serializer.ng_deps.dart' as i23;
import 'utils.ng_deps.dart' as i24;
import 'package:angular2/src/compiler/compiler.ng_deps.dart' as i25;
import 'package:angular2/src/core/linker/dynamic_component_loader.ng_deps.dart' as i26;
import 'package:angular2/src/core/linker/view_manager.ng_deps.dart' as i27;
export 'test_injector.dart';
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
i11.initReflector();
i12.initReflector();
i13.initReflector();
i14.initReflector();
i15.initReflector();
i16.initReflector();
i17.initReflector();
i18.initReflector();
i19.initReflector();
i20.initReflector();
i21.initReflector();
i22.initReflector();
i23.initReflector();
i24.initReflector();
i25.initReflector();
i26.initReflector();
i27.initReflector();
}
