library angular2.transform.template_compiler.generator.ng_deps.dart;

import 'generator.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'dart:async';
import 'package:barback/barback.dart';
import 'package:path/path.dart' as path;
import 'package:angular2/src/core/change_detection/interfaces.dart';
import 'package:angular2/src/facade/lang.dart';
import 'package:angular2/src/core/reflection/reflection.dart';
import 'package:angular2/src/transform/common/asset_reader.dart';
import 'package:angular2/src/transform/common/code/source_module.dart';
import 'package:angular2/src/transform/common/logging.dart';
import 'package:angular2/src/transform/common/model/annotation_model.pb.dart';
import 'package:angular2/src/transform/common/model/import_export_model.pb.dart';
import 'package:angular2/src/transform/common/model/ng_deps_model.pb.dart';
import 'package:angular2/src/transform/common/names.dart';
import 'package:angular2/src/transform/common/ng_compiler.dart';
import 'package:angular2/src/transform/common/zone.dart' as zone;
import 'reflection/processor.dart' as reg;
import 'reflection/reflection_capabilities.dart';
import 'compile_data_creator.dart';
import 'package:angular2/src/core/change_detection/interfaces.ng_deps.dart' as i0;
import 'package:angular2/src/core/reflection/reflection.ng_deps.dart' as i1;
import 'package:angular2/src/transform/common/asset_reader.ng_deps.dart' as i2;
import 'package:angular2/src/transform/common/code/source_module.ng_deps.dart' as i3;
import 'package:angular2/src/transform/common/logging.ng_deps.dart' as i4;
import 'package:angular2/src/transform/common/model/annotation_model.pb.ng_deps.dart' as i5;
import 'package:angular2/src/transform/common/model/import_export_model.pb.ng_deps.dart' as i6;
import 'package:angular2/src/transform/common/model/ng_deps_model.pb.ng_deps.dart' as i7;
import 'package:angular2/src/transform/common/ng_compiler.ng_deps.dart' as i8;
import 'package:angular2/src/transform/common/zone.ng_deps.dart' as i9;
import 'reflection/processor.ng_deps.dart' as i10;
import 'reflection/reflection_capabilities.ng_deps.dart' as i11;
import 'compile_data_creator.ng_deps.dart' as i12;
export 'generator.dart';
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
i11.initReflector();
i12.initReflector();
}
