name: mathedit
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.0'
  browser: '^0.10.0+2'
  dart_to_js_script_rewriter: '^0.1.0+4'
  mathjax: '^0.0.5'
  md_proc: '^0.7.3'
  js: '^0.6.0'
  bootstrap: '^3.3.4'
  github: '^2.3.1'
  usage: '^1.0.1'
  firebase: '^0.6.5'
dev_dependencies:
  coverage: ^0.7.2
  dart_dev: ^1.0.5
  grinder: ^0.8.0+1
  test: ^0.12.6+1
transformers:
- angular2:
     entry_points: web/main.dart
- dart_to_js_script_rewriter
- mathjax
- bootstrap
- $dart2js:
    sourceMaps: true
dependency_overrides:
  mathjax:
    path: ../../packages/mathjax.dart
  dart_to_js_script_rewriter:
    path: ../../AngularProjects/dart_to_js_script_rewriter