name: mathedit
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.0'
  browser: '^0.10.0+2'
  dart_to_js_script_rewriter: '^0.1.0+4'
  mathjax: '^0.0.2'
  md_proc: '^0.7.3'
  js: '^0.6.0'
transformers:
- angular2:
     entry_points: web/main.dart
- dart_to_js_script_rewriter
#
#dependency_overrides:
#  mathjax:
#    path: ../../packages/mathjax.dart