library angular2.src.compiler.compiler.ng_deps.dart;

import 'compiler.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'runtime_compiler.dart' show RuntimeCompiler_;
import 'package:angular2/src/facade/lang.dart' show assertionsEnabled, Type;
import 'package:angular2/src/core/di.dart' show provide, Provider;
import 'package:angular2/src/compiler/template_parser.dart' show TemplateParser;
import 'package:angular2/src/compiler/html_parser.dart' show HtmlParser;
import 'package:angular2/src/compiler/template_normalizer.dart' show TemplateNormalizer;
import 'package:angular2/src/compiler/runtime_metadata.dart' show RuntimeMetadataResolver;
import 'package:angular2/src/compiler/change_detector_compiler.dart' show ChangeDetectionCompiler;
import 'package:angular2/src/compiler/style_compiler.dart' show StyleCompiler;
import 'package:angular2/src/compiler/command_compiler.dart' show CommandCompiler;
import 'package:angular2/src/compiler/template_compiler.dart' show TemplateCompiler;
import 'package:angular2/src/core/change_detection/change_detection.dart' show ChangeDetectorGenConfig;
import 'package:angular2/src/core/linker/compiler.dart' show Compiler;
import 'package:angular2/src/compiler/runtime_compiler.dart' show RuntimeCompiler;
import 'package:angular2/src/compiler/schema/element_schema_registry.dart' show ElementSchemaRegistry;
import 'package:angular2/src/compiler/schema/dom_element_schema_registry.dart' show DomElementSchemaRegistry;
import 'package:angular2/src/compiler/url_resolver.dart' show UrlResolver, DEFAULT_PACKAGE_URL_PROVIDER;
import 'package:angular2/src/core/change_detection/change_detection.dart' show Parser, Lexer;
import 'runtime_compiler.ng_deps.dart' as i0;
import 'package:angular2/src/core/di.ng_deps.dart' as i1;
import 'package:angular2/src/compiler/template_parser.ng_deps.dart' as i2;
import 'package:angular2/src/compiler/html_parser.ng_deps.dart' as i3;
import 'package:angular2/src/compiler/template_normalizer.ng_deps.dart' as i4;
import 'package:angular2/src/compiler/runtime_metadata.ng_deps.dart' as i5;
import 'package:angular2/src/compiler/change_detector_compiler.ng_deps.dart' as i6;
import 'package:angular2/src/compiler/style_compiler.ng_deps.dart' as i7;
import 'package:angular2/src/compiler/command_compiler.ng_deps.dart' as i8;
import 'package:angular2/src/compiler/template_compiler.ng_deps.dart' as i9;
import 'package:angular2/src/core/change_detection/change_detection.ng_deps.dart' as i10;
import 'package:angular2/src/core/linker/compiler.ng_deps.dart' as i11;
import 'package:angular2/src/compiler/runtime_compiler.ng_deps.dart' as i12;
import 'package:angular2/src/compiler/schema/dom_element_schema_registry.ng_deps.dart' as i13;
import 'package:angular2/src/compiler/url_resolver.ng_deps.dart' as i14;
import 'template_compiler.ng_deps.dart' as i15;
import 'directive_metadata.ng_deps.dart' as i16;
import 'source_module.ng_deps.dart' as i17;
import 'package:angular2/src/core/platform_directives_and_pipes.ng_deps.dart' as i18;
import 'package:angular2/src/compiler/template_ast.ng_deps.dart' as i19;
export 'compiler.dart';
export 'template_compiler.dart' show TemplateCompiler;
export 'directive_metadata.dart' show CompileDirectiveMetadata, CompileTypeMetadata, CompileTemplateMetadata;
export 'source_module.dart' show SourceModule, SourceWithImports;
export 'package:angular2/src/core/platform_directives_and_pipes.dart' show PLATFORM_DIRECTIVES, PLATFORM_PIPES;
export 'package:angular2/src/compiler/template_ast.dart';
export 'package:angular2/src/compiler/template_parser.dart' show TEMPLATE_TRANSFORMS;
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
i11.initReflector();
i12.initReflector();
i13.initReflector();
i14.initReflector();
i15.initReflector();
i16.initReflector();
i17.initReflector();
i18.initReflector();
i19.initReflector();
}
