library angular2.src.core.application_common_providers.ng_deps.dart;

import 'application_common_providers.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'package:angular2/src/facade/lang.dart' show Type;
import 'package:angular2/src/core/di.dart' show provide, Provider, Injector, OpaqueToken;
import 'application_tokens.dart' show APP_COMPONENT_REF_PROMISE, APP_COMPONENT, APP_ID_RANDOM_PROVIDER;
import 'change_detection/change_detection.dart' show IterableDiffers, defaultIterableDiffers, KeyValueDiffers, defaultKeyValueDiffers;
import 'linker/view_pool.dart' show AppViewPool, APP_VIEW_POOL_CAPACITY;
import 'linker/view_manager.dart' show AppViewManager;
import 'linker/view_manager.dart' show AppViewManager_;
import 'linker/view_manager_utils.dart' show AppViewManagerUtils;
import 'linker/view_resolver.dart' show ViewResolver;
import 'linker/view_listener.dart' show AppViewListener;
import 'linker/proto_view_factory.dart' show ProtoViewFactory;
import 'linker/directive_resolver.dart' show DirectiveResolver;
import 'linker/pipe_resolver.dart' show PipeResolver;
import 'linker/compiler.dart' show Compiler;
import 'linker/compiler.dart' show Compiler_;
import 'linker/dynamic_component_loader.dart' show DynamicComponentLoader;
import 'linker/dynamic_component_loader.dart' show DynamicComponentLoader_;
import 'package:angular2/src/core/di.ng_deps.dart' as i0;
import 'application_tokens.ng_deps.dart' as i1;
import 'change_detection/change_detection.ng_deps.dart' as i2;
import 'linker/view_pool.ng_deps.dart' as i3;
import 'linker/view_manager.ng_deps.dart' as i4;
import 'linker/view_manager_utils.ng_deps.dart' as i5;
import 'linker/view_resolver.ng_deps.dart' as i6;
import 'linker/view_listener.ng_deps.dart' as i7;
import 'linker/proto_view_factory.ng_deps.dart' as i8;
import 'linker/directive_resolver.ng_deps.dart' as i9;
import 'linker/pipe_resolver.ng_deps.dart' as i10;
import 'linker/compiler.ng_deps.dart' as i11;
import 'linker/dynamic_component_loader.ng_deps.dart' as i12;
export 'application_common_providers.dart';
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
i11.initReflector();
i12.initReflector();
}
