library angular2.src.core.application_ref.ng_deps.dart;

import 'application_ref.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'package:angular2/src/core/zone/ng_zone.dart' show NgZone;
import 'package:angular2/src/facade/lang.dart' show Type, isBlank, isPresent, assertionsEnabled, print, IS_DART;
import 'package:angular2/src/core/di.dart' show provide, Provider, Injector, OpaqueToken;
import 'application_tokens.dart' show APP_COMPONENT_REF_PROMISE, APP_COMPONENT, APP_ID_RANDOM_PROVIDER, PLATFORM_INITIALIZER, APP_INITIALIZER;
import 'package:angular2/src/facade/async.dart' show Future, PromiseWrapper, PromiseCompleter, ObservableWrapper;
import 'package:angular2/src/facade/collection.dart' show ListWrapper;
import 'package:angular2/src/core/testability/testability.dart' show TestabilityRegistry, Testability;
import 'package:angular2/src/core/linker/dynamic_component_loader.dart' show ComponentRef, DynamicComponentLoader;
import 'package:angular2/src/facade/exceptions.dart' show BaseException, WrappedException, ExceptionHandler, unimplemented;
import 'package:angular2/src/core/linker/view_ref.dart' show internalView;
import 'package:angular2/src/core/console.dart' show Console;
import 'profile/profile.dart' show wtfLeave, wtfCreateScope, WtfScopeFn;
import 'package:angular2/src/core/change_detection/change_detector_ref.dart' show ChangeDetectorRef;
import 'package:angular2/src/facade/lang.dart' show lockMode;
import 'package:angular2/src/core/zone/ng_zone.ng_deps.dart' as i0;
import 'package:angular2/src/core/di.ng_deps.dart' as i1;
import 'application_tokens.ng_deps.dart' as i2;
import 'package:angular2/src/facade/async.ng_deps.dart' as i3;
import 'package:angular2/src/core/testability/testability.ng_deps.dart' as i4;
import 'package:angular2/src/core/linker/dynamic_component_loader.ng_deps.dart' as i5;
import 'package:angular2/src/facade/exceptions.ng_deps.dart' as i6;
import 'package:angular2/src/core/linker/view_ref.ng_deps.dart' as i7;
import 'package:angular2/src/core/console.ng_deps.dart' as i8;
import 'profile/profile.ng_deps.dart' as i9;
import 'package:angular2/src/core/change_detection/change_detector_ref.ng_deps.dart' as i10;
export 'application_ref.dart';
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
}
