library angular2.src.core.linker.view.ng_deps.dart;

import 'view.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'package:angular2/src/facade/collection.dart' show ListWrapper, MapWrapper, Map, StringMapWrapper;
import 'package:angular2/src/core/change_detection/change_detection.dart' show ChangeDetector, ChangeDispatcher, DirectiveIndex, BindingTarget, Locals, ProtoChangeDetector;
import 'package:angular2/src/core/change_detection/interfaces.dart' show DebugContext;
import 'element_injector.dart' show ProtoElementInjector, ElementInjector, PreBuiltObjects, DirectiveProvider;
import 'element_binder.dart' show ElementBinder;
import 'package:angular2/src/facade/lang.dart' show isPresent;
import 'package:angular2/src/facade/exceptions.dart' show BaseException, WrappedException;
import 'package:angular2/src/core/render/api.dart' as renderApi;
import 'package:angular2/src/core/render/api.dart' show RenderEventDispatcher;
import 'view_ref.dart' show ViewRef, ProtoViewRef, internalView;
import 'element_ref.dart' show ElementRef;
import 'package:angular2/src/core/pipes/pipes.dart' show ProtoPipes;
import 'package:angular2/src/core/render/util.dart' show camelCaseToDashCase;
import 'template_commands.dart' show TemplateCmd;
import 'view_ref.dart' show ViewRef_, ProtoViewRef_;
import 'package:angular2/src/core/change_detection/change_detection.ng_deps.dart' as i0;
import 'package:angular2/src/core/change_detection/interfaces.ng_deps.dart' as i1;
import 'element_injector.ng_deps.dart' as i2;
import 'element_binder.ng_deps.dart' as i3;
import 'package:angular2/src/facade/exceptions.ng_deps.dart' as i4;
import 'package:angular2/src/core/render/api.ng_deps.dart' as i5;
import 'view_ref.ng_deps.dart' as i6;
import 'element_ref.ng_deps.dart' as i7;
import 'package:angular2/src/core/pipes/pipes.ng_deps.dart' as i8;
import 'package:angular2/src/core/render/util.ng_deps.dart' as i9;
import 'template_commands.ng_deps.dart' as i10;
export 'view.dart';
export 'package:angular2/src/core/change_detection/interfaces.dart' show DebugContext;
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
}
