library angular2.src.platform.browser_common.ng_deps.dart;

import 'browser_common.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'package:angular2/src/facade/lang.dart' show IS_DART;
import 'package:angular2/src/core/di.dart' show provide, Provider, Injector, OpaqueToken;
import 'package:angular2/core.dart' show PLATFORM_INITIALIZER, PLATFORM_DIRECTIVES, PLATFORM_PIPES, ComponentRef, platform, ExceptionHandler, Reflector, Renderer, reflector, APPLICATION_COMMON_PROVIDERS, PLATFORM_COMMON_PROVIDERS;
import 'package:angular2/common.dart' show COMMON_DIRECTIVES, COMMON_PIPES, FORM_PROVIDERS;
import 'package:angular2/src/core/testability/testability.dart' show Testability;
import 'package:angular2/src/platform/dom/dom_adapter.dart' show DOM;
import 'package:angular2/src/platform/dom/events/dom_events.dart' show DomEventsPlugin;
import 'package:angular2/src/platform/dom/events/key_events.dart' show KeyEventsPlugin;
import 'package:angular2/src/platform/dom/events/hammer_gestures.dart' show HammerGesturesPlugin;
import 'package:angular2/src/platform/dom/dom_tokens.dart' show DOCUMENT;
import 'package:angular2/src/platform/dom/dom_renderer.dart' show DomRenderer, DomRenderer_;
import 'package:angular2/src/platform/dom/shared_styles_host.dart' show DomSharedStylesHost;
import 'package:angular2/src/platform/dom/shared_styles_host.dart' show SharedStylesHost;
import 'package:angular2/src/animate/browser_details.dart' show BrowserDetails;
import 'package:angular2/src/animate/animation_builder.dart' show AnimationBuilder;
import 'browser/browser_adapter.dart' show BrowserDomAdapter;
import 'package:angular2/src/platform/browser/testability.dart' show BrowserGetTestability;
import 'package:angular2/src/core/profile/wtf_init.dart' show wtfInit;
import 'package:angular2/src/platform/dom/events/event_manager.dart' show EventManager, EVENT_MANAGER_PLUGINS;
import 'package:angular2/src/core/di.ng_deps.dart' as i0;
import 'package:angular2/core.ng_deps.dart' as i1;
import 'package:angular2/common.ng_deps.dart' as i2;
import 'package:angular2/src/core/testability/testability.ng_deps.dart' as i3;
import 'package:angular2/src/platform/dom/dom_adapter.ng_deps.dart' as i4;
import 'package:angular2/src/platform/dom/events/dom_events.ng_deps.dart' as i5;
import 'package:angular2/src/platform/dom/events/key_events.ng_deps.dart' as i6;
import 'package:angular2/src/platform/dom/events/hammer_gestures.ng_deps.dart' as i7;
import 'package:angular2/src/platform/dom/dom_tokens.ng_deps.dart' as i8;
import 'package:angular2/src/platform/dom/dom_renderer.ng_deps.dart' as i9;
import 'package:angular2/src/platform/dom/shared_styles_host.ng_deps.dart' as i10;
import 'package:angular2/src/animate/browser_details.ng_deps.dart' as i11;
import 'package:angular2/src/animate/animation_builder.ng_deps.dart' as i12;
import 'browser/browser_adapter.ng_deps.dart' as i13;
import 'package:angular2/src/platform/browser/testability.ng_deps.dart' as i14;
import 'package:angular2/src/core/profile/wtf_init.ng_deps.dart' as i15;
import 'package:angular2/src/platform/dom/events/event_manager.ng_deps.dart' as i16;
import 'package:angular2/src/platform/browser/title.ng_deps.dart' as i17;
import 'package:angular2/platform/common_dom.ng_deps.dart' as i18;
import 'package:angular2/src/platform/browser/tools/tools.ng_deps.dart' as i19;
export 'browser_common.dart';
export 'package:angular2/src/platform/dom/dom_tokens.dart' show DOCUMENT;
export 'package:angular2/src/platform/browser/title.dart' show Title;
export 'package:angular2/platform/common_dom.dart' show DebugElementViewListener, ELEMENT_PROBE_PROVIDERS, ELEMENT_PROBE_BINDINGS, inspectNativeElement, By;
export 'browser/browser_adapter.dart' show BrowserDomAdapter;
export 'package:angular2/src/platform/browser/tools/tools.dart' show enableDebugTools, disableDebugTools;
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
i11.initReflector();
i12.initReflector();
i13.initReflector();
i14.initReflector();
i15.initReflector();
i16.initReflector();
i17.initReflector();
i18.initReflector();
i19.initReflector();
}
