library angular2.src.core.change_detection.abstract_change_detector.ng_deps.dart;

import 'abstract_change_detector.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'package:angular2/src/facade/lang.dart' show assertionsEnabled, isPresent, isBlank, StringWrapper;
import 'package:angular2/src/facade/collection.dart' show ListWrapper;
import 'change_detection_util.dart' show ChangeDetectionUtil;
import 'change_detector_ref.dart' show ChangeDetectorRef, ChangeDetectorRef_;
import 'directive_record.dart' show DirectiveIndex;
import 'interfaces.dart' show ChangeDetector, ChangeDispatcher;
import 'pipes.dart' show Pipes;
import 'exceptions.dart' show ChangeDetectionError, ExpressionChangedAfterItHasBeenCheckedException, DehydratedException;
import 'binding_record.dart' show BindingTarget;
import 'parser/locals.dart' show Locals;
import 'constants.dart' show ChangeDetectionStrategy, ChangeDetectorState;
import '../profile/profile.dart' show wtfCreateScope, wtfLeave, WtfScopeFn;
import 'observable_facade.dart' show isObservable;
import 'change_detection_util.ng_deps.dart' as i0;
import 'change_detector_ref.ng_deps.dart' as i1;
import 'directive_record.ng_deps.dart' as i2;
import 'interfaces.ng_deps.dart' as i3;
import 'pipes.ng_deps.dart' as i4;
import 'exceptions.ng_deps.dart' as i5;
import 'binding_record.ng_deps.dart' as i6;
import 'parser/locals.ng_deps.dart' as i7;
import 'constants.ng_deps.dart' as i8;
import '../profile/profile.ng_deps.dart' as i9;
import 'observable_facade.ng_deps.dart' as i10;
export 'abstract_change_detector.dart';
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
}
