library angular2.src.core.change_detection.proto_change_detector.ng_deps.dart;

import 'proto_change_detector.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'package:angular2/src/facade/lang.dart' show Type, isBlank, isPresent, isString;
import 'package:angular2/src/facade/exceptions.dart' show BaseException;
import 'package:angular2/src/facade/collection.dart' show ListWrapper, MapWrapper, StringMapWrapper;
import 'parser/ast.dart' show PropertyRead, PropertyWrite, KeyedWrite, AST, ASTWithSource, AstVisitor, Binary, Chain, Conditional, BindingPipe, FunctionCall, ImplicitReceiver, Interpolation, KeyedRead, LiteralArray, LiteralMap, LiteralPrimitive, MethodCall, PrefixNot, Quote, SafePropertyRead, SafeMethodCall;
import 'interfaces.dart' show ChangeDetector, ProtoChangeDetector, ChangeDetectorDefinition;
import 'change_detection_util.dart' show ChangeDetectionUtil;
import 'dynamic_change_detector.dart' show DynamicChangeDetector;
import 'binding_record.dart' show BindingRecord, BindingTarget;
import 'directive_record.dart' show DirectiveRecord, DirectiveIndex;
import 'event_binding.dart' show EventBinding;
import 'coalesce.dart' show coalesce;
import 'proto_record.dart' show ProtoRecord, RecordType;
import 'package:angular2/src/facade/exceptions.ng_deps.dart' as i0;
import 'parser/ast.ng_deps.dart' as i1;
import 'interfaces.ng_deps.dart' as i2;
import 'change_detection_util.ng_deps.dart' as i3;
import 'dynamic_change_detector.ng_deps.dart' as i4;
import 'binding_record.ng_deps.dart' as i5;
import 'directive_record.ng_deps.dart' as i6;
import 'event_binding.ng_deps.dart' as i7;
import 'coalesce.ng_deps.dart' as i8;
import 'proto_record.ng_deps.dart' as i9;
export 'proto_change_detector.dart';
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
}
