library angular2.core.ng_deps.dart;

import 'core.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import './src/core/metadata.ng_deps.dart' as i0;
import './src/core/di.ng_deps.dart' as i1;
import './src/facade/facade.ng_deps.dart' as i2;
import './src/core/application_ref.ng_deps.dart' as i3;
import './src/core/application_tokens.ng_deps.dart' as i4;
import './src/core/zone.ng_deps.dart' as i5;
import './src/core/render.ng_deps.dart' as i6;
import './src/core/linker.ng_deps.dart' as i7;
import './src/core/debug/debug_element.ng_deps.dart' as i8;
import './src/core/testability/testability.ng_deps.dart' as i9;
import './src/core/change_detection.ng_deps.dart' as i10;
import './src/core/platform_directives_and_pipes.ng_deps.dart' as i11;
import './src/core/platform_common_providers.ng_deps.dart' as i12;
import './src/core/application_common_providers.ng_deps.dart' as i13;
import './src/core/reflection/reflection.ng_deps.dart' as i14;
export 'core.dart';
export './src/core/metadata.dart';
export './src/core/util.dart';
export 'package:angular2/src/facade/lang.dart' show enableProdMode;
export './src/core/di.dart' hide ForwardRefFn, resolveForwardRef, forwardRef;
export './src/facade/facade.dart';
export './src/core/application_ref.dart' show platform, createNgZone, PlatformRef, ApplicationRef;
export './src/core/application_tokens.dart' show APP_ID, APP_COMPONENT, APP_INITIALIZER, PACKAGE_ROOT_URL, PLATFORM_INITIALIZER;
export './src/core/zone.dart';
export './src/core/render.dart';
export './src/core/linker.dart';
export './src/core/debug/debug_element.dart' show DebugElement, Scope, inspectElement, asNativeElements;
export './src/core/testability/testability.dart';
export './src/core/change_detection.dart';
export './src/core/platform_directives_and_pipes.dart';
export './src/core/platform_common_providers.dart';
export './src/core/application_common_providers.dart';
export './src/core/reflection/reflection.dart';
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
i11.initReflector();
i12.initReflector();
i13.initReflector();
i14.initReflector();
}
