library angular2.router.ng_deps.dart;

import 'router.dart';
import 'package:angular2/src/core/reflection/reflection.dart' as _ngRef;
import 'src/router/platform_location.dart' show PlatformLocation;
import 'src/router/location_strategy.dart' show LocationStrategy;
import 'src/router/path_location_strategy.dart' show PathLocationStrategy;
import 'src/router/router.dart' show Router, RootRouter;
import 'src/router/router_outlet.dart' show RouterOutlet;
import 'src/router/router_link.dart' show RouterLink;
import 'src/router/route_registry.dart' show RouteRegistry, ROUTER_PRIMARY_COMPONENT;
import 'src/router/location.dart' show Location;
import 'package:angular2/core.dart' show ApplicationRef, provide, OpaqueToken, Provider;
import 'package:angular2/src/facade/exceptions.dart' show BaseException;
import 'src/router/platform_location.ng_deps.dart' as i0;
import 'src/router/location_strategy.ng_deps.dart' as i1;
import 'src/router/path_location_strategy.ng_deps.dart' as i2;
import 'src/router/router.ng_deps.dart' as i3;
import 'src/router/router_outlet.ng_deps.dart' as i4;
import 'src/router/router_link.ng_deps.dart' as i5;
import 'src/router/route_registry.ng_deps.dart' as i6;
import 'src/router/location.ng_deps.dart' as i7;
import 'package:angular2/core.ng_deps.dart' as i8;
import 'package:angular2/src/facade/exceptions.ng_deps.dart' as i9;
import 'src/router/instruction.ng_deps.dart' as i10;
import 'src/router/hash_location_strategy.ng_deps.dart' as i11;
import 'src/router/route_config_decorator.ng_deps.dart' as i12;
import 'src/router/interfaces.ng_deps.dart' as i13;
import 'src/router/lifecycle_annotations.ng_deps.dart' as i14;
export 'router.dart';
export 'src/router/router.dart' show Router;
export 'src/router/router_outlet.dart' show RouterOutlet;
export 'src/router/router_link.dart' show RouterLink;
export 'src/router/instruction.dart' show RouteParams, RouteData;
export 'src/router/platform_location.dart' show PlatformLocation;
export 'src/router/route_registry.dart' show RouteRegistry, ROUTER_PRIMARY_COMPONENT;
export 'src/router/location_strategy.dart' show LocationStrategy, APP_BASE_HREF;
export 'src/router/hash_location_strategy.dart' show HashLocationStrategy;
export 'src/router/path_location_strategy.dart' show PathLocationStrategy;
export 'src/router/location.dart' show Location;
export 'src/router/route_config_decorator.dart';
export 'src/router/route_definition.dart';
export 'src/router/interfaces.dart' show OnActivate, OnDeactivate, OnReuse, CanDeactivate, CanReuse;
export 'src/router/lifecycle_annotations.dart' show CanActivate;
export 'src/router/instruction.dart' show Instruction, ComponentInstruction;
export 'package:angular2/core.dart' show OpaqueToken;
var _visited = false;
void initReflector() {
if (_visited) return; _visited = true;
_ngRef.reflector
..registerSetters({'routeParams': (o, v) => o.routeParams = v, 'target': (o, v) => o.target = v})
;
i0.initReflector();
i1.initReflector();
i2.initReflector();
i3.initReflector();
i4.initReflector();
i5.initReflector();
i6.initReflector();
i7.initReflector();
i8.initReflector();
i9.initReflector();
i10.initReflector();
i11.initReflector();
i12.initReflector();
i13.initReflector();
i14.initReflector();
}
